# Generated by Django 3.0.2 on 2020-01-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_list',
            name='image_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
